# Generated by Django 3.1.1 on 2021-07-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('git_url', models.URLField(blank=True, null=True)),
                ('is_personal', models.BooleanField(default=False)),
                ('is_professional', models.BooleanField(default=False)),
                ('is_deployed', models.BooleanField(default=False)),
                ('deploy_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_pics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
