# Generated by Django 3.2.5 on 2021-07-26 05:14

import django.core.validators
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('email', models.CharField(max_length=255)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('phone_number', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')])),
                ('contact_details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
