# Generated by Django 3.2.5 on 2021-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210726_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
